# Generated by Django 3.1.5 on 2021-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210326_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
